### ISSUE TITLE
Need a 0.11 version

### ISSUE THREAD

**Issue by AjithKumar-Raj** [terraform-aws-modules/terraform-aws-cloudwatch#1]
I am new to terraform world.
I was stuck in variable.tf for number type define.
Can @antonbabenko  help me to sort this?

**Comment by antonbabenko** [comment]
This module will not support 0.11, because the way it is written and it is not feasible to rewrite it to support 0.11.

You can maybe find something for your needs in the Terraform Registry - https://registry.terraform.io/search?q=cloudwatch
