### ISSUE TITLE
Anomaly detection metric alarm?

### ISSUE THREAD

**Issue by NeckBeardPrince** [terraform-aws-modules/terraform-aws-cloudwatch#13]
Looks like the ThresholdMetricId is required but the module doesn't support it.
Error: Creating metric alarm failed: ValidationError: ComparisonOperators for ranges require ThresholdMetricId to be set
        status code: 400, request id: e863e3a6-aa16-41a5-875c-d363c65c32fb

**Comment by BarryDuggan** [comment]
I've experienced the same issue today when trying to create an anomaly detection metric alarm.
threshold_metric_id is an unsupported argument in the module but cloudwatch requires it

**Comment by NeckBeardPrince** [comment]
Was this ever resolved?

**Comment by antonbabenko** [comment]
PR with an updated example is welcome if you think it is missing.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.5.0 :tada:
