### ISSUE TITLE
Add account_id input for cross account metric alerts

### ISSUE THREAD

**Issue by monkies** [terraform-aws-modules/terraform-aws-cloudwatch#24]
Cross account metric alarms were adding in early August and added to the Terraform provider in v3.54.0

https://aws.amazon.com/about-aws/whats-new/2021/08/announcing-amazon-cloudwatch-cross-account-alarms/
https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.54.0
- resource/aws_cloudwatch_metric_alarm: Add support for account_id (#20541)

Can we please get the account_id input added. 

in the resource as below

    metric_query {
        id          = "m1"
        account_id  = "123456789" // <-- new attribute
        return_data = true
        
        metric {
            metric_name = "HealthyHostCount"
            namespace   = "AWS/NetworkELB"
            dimentions  = {
                LoadBalancer = "some nlb"
                TargetGroup  = "some tg"
            }
            period  = 60
            stat    = "average"
        }
    }

**Comment by antonbabenko** [comment]
Please submit a PR for this feature.

**Comment by maunzCache** [comment]
I am interested on that feature as well :)

**Comment by maunzCache** [comment]
@antonbabenko Would be glad if you could review my PR :)
