### ISSUE TITLE
Support custom prefix for CIS alarms

### ISSUE THREAD

**Issue by ryanoolala** [terraform-aws-modules/terraform-aws-cloudwatch#28]
## Is your request related to a problem? Please describe.

The CIS alarm name does not allow for custom prefixes, this creates a problem if you manage multiple accounts and the alarm will not include any information of which account this is coming from.

## Describe the solution you'd like.

Add a variable to allow the module user to set the prefix they want so that they can use meaningful names for identification, and not have to rely on random pet names for dynamic alarm names

## Describe alternatives you've considered.

Creating multiple receivers, whether it is email/chat groups etc just to separate which alarm is for which account

**Comment by antonbabenko** [comment]
Hi!

This sounds like a valid use case. PR is welcome.

**Comment by ryanoolala** [comment]
Hello, created one for review please

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.3.0 :tada:
