### ISSUE TITLE
support for `aws_cloudwatch_log_subscription_filter` resource

### ISSUE THREAD

**Issue by pyo-counting** [terraform-aws-modules/terraform-aws-cloudwatch#68]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

It's not a new feature. And i can't find in CHANGELOG.md when `aws_cloudwatch_log_subscription_filter` resource was added.

Please consider adding this resource for CloudWatch [subscription filter](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Subscriptions.html).

**Comment by magreenbaum** [comment]
Closed by: https://github.com/terraform-aws-modules/terraform-aws-cloudwatch/pull/69
